#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS app_user;
    GRANT ALL PRIVILEGES ON DATABASE app_user TO $POSTGRES_USER;
EOSQL